apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: /.config/kustomize/plugin/viaduct.ai/v1/ksops/ksops 
files: 
  - development-cluster.enc.yaml
  # - production-cluster.enc.yaml
