apiVersion: v1
data:
    dex.github.clientSecret: ENC[AES256_GCM,data:2zujfb0dXOjKSTms7UJREakjIdYWDXWo,iv:y04KuB5Z5ZijyNfJ7wLHolReVeYxOFL5UEDeavCSOcc=,tag:UtPA80n+Y4pPjVjkpAF+5g==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: github_connector_secret
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zge2l5uxpph0x3u0qg53h8jg8mf0m6kce249lv73nv7e9mwc3chq92f6cj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkK0QrNlZZWC9KVkE3bjgx
            QjIxMGpCZzZNcWo1dUY5aUc5VFk0U0RRdlFFCllUVEhhVlk3c1p0MG5LRHJSYURI
            ZFlJNnBKQ0dxeGF2cHBDUzIwdEtDMkEKLS0tIHoxUmo3R3lvZ0lTY2FZQ0YwTzlP
            Z0lXUE9ib2hMK21sa0hwWWNOUE5MU2MKUpxFX0BwKo5qFLqMmVvz2Rj8p7B9n5Hl
            yuHX49tHCnZbLyfrX6jqG9dSD7Ud8DBWGsbucQqMGEE90XChQL9EaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-08T13:35:12Z"
    mac: ENC[AES256_GCM,data:IXkDaBp4xC1BOscxlq0deIPrVq+sRYn4zuN5e8Q/lv8P79mIKvaD5GFUSt9mOT1QNWvJEfXiu5KCNYxbXHkKR58P76jmrKF+lRe0M/Ow0YVEpG42YombZR3I2VhlV9cAhgghba/DqopEgKpJPjyCEtq+ly8v+T2mhs4vRx1wTY0=,iv:iRSnTM5drAxp5oOiO9NeyJe94keptYoN/lqRJAiTSXg=,tag:oM4ig1kWgZU4R+WLK0iMkg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
