apiVersion: v1
kind: Secret
metadata:
    name: gitops-repo
    namespace: argocd
    labels:
        argocd.argoproj.io/secret-type: repository
stringData:
    type: ENC[AES256_GCM,data:YVrg,iv:iZdifHe58IWvsDAWz1cIKSr9TpOR9nclO8yySKID2JY=,tag:k9tZdJWn2JG8jMSp7hH4dg==,type:str]
    url: ENC[AES256_GCM,data:fzetZ1hE0Q/6VcouHx5rhGuNfu++sk1GfkLNmxeRPLrTr0oZi2Urcugc,iv:Ljr5N/kaR38pnig3tol5dssmvZCvG+Kdxc1yDar82z0=,tag:UDQWvv9LXeSdOikQ1XJVmA==,type:str]
    password: ENC[AES256_GCM,data:PXZkpKOI,iv:tjGaPktIJsWEIo4o0v5rMjsV+6vQzM4UDAjk1Kx31n0=,tag:KVwz2wAqNNDUYUsItQr5Pw==,type:str]
    username: ENC[AES256_GCM,data:+1eb5TY6xtYkjgbtp2ORMVBFNfxub+3CWvMjymGoxJdNNgkJe73coUaX3LclMJ1NK31zWLuue/JTWJ3gK923OdxE1A1xBijQIbqehpv7nadL7kpNigbmb6QMU5y7,iv:0f9DBQXLYtIseVR3t+isZBzfWJwhH3r8gOUM4beK4nI=,tag:6/iSCLjq4dgkD4ERaAFH5w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zge2l5uxpph0x3u0qg53h8jg8mf0m6kce249lv73nv7e9mwc3chq92f6cj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIV1ZoeWFWQUVxZXVzUXdQ
            OGV3YWh4dndrRXo1SnZ1WG1aWTR5NWo5aFZzCm84ajdjV2RsMWhDWldQenRxaE9E
            Nk5FUExYNEJUcjlHTC9qQjBTVmg1NU0KLS0tIGdFUndmc205aEFsckN2cFNqVWRr
            dm9lV21wNFZwTHBDRDdJcWVIbk1nMkUKX9EO3yK7zxngqgbZA8gpBxh6u3W+auSr
            TESf3iPQTkM9Y3sbYTdVpDY5rOsG1wj07NvMaPy9HlYS9odEQK2fYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-14T09:46:16Z"
    mac: ENC[AES256_GCM,data:Zr0ss2EnxnyndGR53T/PIiC6/8Z13h3Sv+lFtEO3IV7TvbiAZWqfVdn5R25Dqw4GWu7k/b84jG9Jyl82EMfVyUev1u/a/w9HQyeLjaJqGoc2/NWgdkEZUzuNh5aXMKFnoh2Edf+fNRzSFnxRyhkzvPDroLPVqYXL+d2Le+8XntE=,iv:TPHcwwBtD5Gvv2hXRQvMILpTnJtahl0zedIBWn0ACWk=,tag:HjKmy6yuIKyOGP+EQB+rKQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
