apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: enable-exec 
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: 
  project: default
  source:
    path: enable-exec 
    repoURL: https://github.com/zMynxx/rethink-argo.git
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
    - allowEmpty=true
