apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
  - path: kustomize-flags.patch.yaml
    target:
      kind: ConfigMap
      name: argocd-cm
      namespace: argocd
  - path: ksops-init-container.patch.yaml
    target:
      kind: Deployment
      name: argocd-repo-server
      namespace: argocd
