apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  url: https://argocd.develeap.com
  accounts.developer: login
  accounts.developer.enabled: 'true'
  accounts.devops: login
  accounts.devops.enabled: 'true'
