apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [development-project.yaml, production-project.yaml]
patches: 
  - path: argocd-cm.yaml
    target:
      kind: ConfigMap
      name: argocd-cm
      namespace: argocd
  - path: argocd-rbac-cm.yaml
    target:
      kind: ConfigMap
      name: argocd-rbac-cm
      namespace: argocd
