apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: /usr/local/bin/ksops 
files: 
  - ./test.enc.yaml
# - development-cluster.enc.yaml
# - production-cluster.enc.yaml
